// Top-level tests
import './base64.js'
import './extensionsEqual.js'
// import './groupinfo.js' // Commented out - requires @noble/curves package

// Codec tests
import './codec/authenticatedContent.js'
import './codec/capabilities.js'
import './codec/commit.js'
import './codec/composite.js'
import './codec/contentType.js'
import './codec/credential.js'
import './codec/credentialType.js'
import './codec/encryptedGroupSecrets.js'
import './codec/extension.js'
import './codec/extensionType.js'
import './codec/externalSender.js'
import './codec/framedContent.js'
import './codec/groupContext.js'
import './codec/groupInfo.js'
import './codec/groupSecrets.js'
import './codec/hpkeCiphertext.js'
import './codec/keyPackage.js'
import './codec/keyPackageTBS.js'
import './codec/leafNode.js'
import './codec/leafNodeData.js'
import './codec/leafNodeSource.js'
import './codec/lifetime.js'
import './codec/message.js'
import './codec/nodeType.js'
import './codec/number.js'
import './codec/optional.js'
import './codec/padding.js'
import './codec/parentHash.js'
import './codec/parentNode.js'
import './codec/presharedkey.js'
import './codec/privateContentAAD.js'
import './codec/privateMessage.js'
import './codec/proposal.js'
import './codec/proposalOrRef.js'
import './codec/proposalOrRefType.js'
import './codec/proposalType.js'
import './codec/protocolVersion.js'
import './codec/pskId.js'
import './codec/pskInfo.js'
import './codec/pskLabel.js'
import './codec/pskType.js'
import './codec/publicMessage.js'
import './codec/ratchetTree.js'
import './codec/requiredCapabilities.js'
import './codec/resumptionPSKUsage.js'
import './codec/reuseGuard.js'
import './codec/sender.js'
import './codec/senderData.js'
import './codec/senderDataAAD.js'
import './codec/senderType.js'
import './codec/transcriptHash.js'
import './codec/treeHash.js'
import './codec/updatePath.js'
import './codec/updatePathNode.js'
import './codec/varLengthEncoding.js'
import './codec/welcome.js'
import './codec/wireformat.js'

// Crypto tests
import './crypto/aead.js'
import './crypto/hpke.js'

// Scenario tests
import './scenario/customExtensions.js'
import './scenario/customProposal.js'
import './scenario/epochOutOfOrder.js'
import './scenario/externalAddProposal.js'
import './scenario/externalJoin.js'
import './scenario/externalJoinResync.js'
import './scenario/externalProposal.js'
import './scenario/externalPsk.js'
import './scenario/externalPskJoin.js'
import './scenario/generationOutOfOrder.js'
import './scenario/grease.js'
import './scenario/groupInfoExtensions.js'
import './scenario/largeGroupFullLifecycle.js'
import './scenario/leaveProposal.js'
import './scenario/multipleJoinsAtOnce.js'
import './scenario/oneToOneJoin.js'
import './scenario/ratchetTreeExtension.js'
import './scenario/reinit.js'
import './scenario/rejectIncomingMessage.js'
import './scenario/remove.js'
import './scenario/requiredCapabilites.js'
import './scenario/resumption.js'
import './scenario/threePartyJoin.js'
import './scenario/update.js'

// Test-vectors tests
import './test-vectors/cryptoBasics.js'
import './test-vectors/deserialization.js'
import './test-vectors/keySchedule.js'
import './test-vectors/messageProtection.js'
import './test-vectors/messages.js'
import './test-vectors/passiveClientScenarios.js'
import './test-vectors/pskSecret.js'
import './test-vectors/secretTree.js'
import './test-vectors/transcriptHashes.js'
import './test-vectors/treekem.js'
import './test-vectors/treemath.js'
import './test-vectors/treeOperations.js'
import './test-vectors/treeValidation.js'
import './test-vectors/welcome.js'

// Validation tests
import './validation/proposalValidation.js'
import './validation/ratchetTreeValidation.js'
import './validation/resumptionValidation.js'
