// Every test that fans out over the ciphersuite matrix, which is where
// nearly all of the running time goes. Setting MLS_SUITES narrows the
// fan-out, so CI can run this entry as several parallel shards -- see
// test/helpers/suite-filter.ts.
// Top-level tests
import './key-schedule.js'

// Scenario tests
import './scenario/add-with-path.js'
import './scenario/custom-extensions.js'
import './scenario/cross-group-replay.js'
import './scenario/custom-proposal.js'
import './scenario/custom-proposal-rejection.js'
import './scenario/custom-proposal-update-path.js'
import './scenario/epoch-out-of-order.js'
import './scenario/external-add-proposal.js'
import './scenario/external-commit-proposal-restrictions.js'
import './scenario/external-commit-unrelated-remove.js'
import './scenario/external-init-sender-policy.js'
import './scenario/external-join.js'
import './scenario/external-join-resync.js'
import './scenario/external-proposal.js'
import './scenario/external-proposal-restricted-types.js'
import './scenario/external-psk.js'
import './scenario/external-psk-join.js'
import './scenario/external-sender-policy.js'
import './scenario/gce-committer-leaf-validation.js'
import './scenario/gce-empty-extensions.js'
import './scenario/generation-out-of-order.js'
import './scenario/grease.js'
import './scenario/group-info-extensions.js'
import './scenario/join-group-init-key-zeroization.js'
import './scenario/large-group-full-lifecycle.js'
import './scenario/leaf-width-update-path.js'
import './scenario/leave-proposal.js'
import './scenario/multiple-joins-at-once.js'
import './scenario/one-to-one-join.js'
import './scenario/proposal-epoch-mismatch.js'
import './scenario/psk-private-message.js'
import './scenario/psk-proposal-usage-policy.js'
import './scenario/ratchet-tree-extension.js'
import './scenario/reinit.js'
import './scenario/reject-incoming-message.js'
import './scenario/remove.js'
import './scenario/required-capabilites.js'
import './scenario/require-update-path.js'
import './scenario/resumption.js'
import './scenario/three-party-join.js'
import './scenario/update.js'
import './scenario/update-path-ciphertext-count.js'

// Validation tests
import './validation/parent-hash-resolution.js'
import './validation/proposal-validation.js'
import './validation/lifetime-validation.js'
import './validation/lifetime-on-receive.js'
import './validation/ratchet-tree-validation.js'
import './validation/resumption-validation.js'
import './validation/psk-field-validation.js'
import './validation/unmerged-leaves-validation.js'
import './validation/update-path-key-uniqueness.js'
import './validation/add-key-uniqueness.js'
import './validation/key-material-retention.js'
import './validation/prior-state-reuse.js'
import './validation/aead-key-zeroization.js'
import './validation/derived-key-matches-advertised.js'
import './validation/credential-continuity.js'
import './validation/credential-capability-floor.js'
import './validation/auth-service-opt-in.js'
import './validation/removed-from-group.js'
import './validation/external-senders-join.js'
import './validation/welcome-path-derivation.js'
import './validation/version-and-last-leaf.js'
