// Every test that runs once regardless of the ciphersuite matrix. This
// entry is not shardable and does not need to be: it is a small
// fraction of the total running time.
// Top-level tests
import './base64.js'
import './suite-filter.js'
import './ciphersuite.js'
import './extensions-equal.js'
import './key-package.js'
import './lifetime.js'
import './transcript-hash-epoch0.js'
import './grease.js'
import './custom-credential.js'
import './util/enum-helpers.js'

// Example app tests
import './example/tree-view.js'
import './example/participants.js'
import './example/routing.js'
import './example/nav.js'
import './example/demo-actions.js'
import './example/persistence-storage.js'
import './example/member-store.js'
import './example/device-sync.js'
import './example/device-restore.js'
import './example/storage-persistence.js'
import './example/storage-panel.js'
import './example/devices.js'
import './example/user.js'
import './example/user-highlight.js'
import './example/card-header.js'
import './example/device-info.js'
import './example/device-info-panel.js'
import './example/device-rotation.js'
import './example/device-removal.js'
import './example/send-plan.js'
import './example/message-view.js'
import './example/message-box.js'
import './example/how-to-use.js'

// Realistic demo tests
import './example-realistic-demo/protocol.js'
import './example-realistic-demo/room-logic.js'
import './example-realistic-demo/delivery-cursor.js'
import './example-realistic-demo/entry-queue.js'
import './example-realistic-demo/state.js'
import './example-realistic-demo/mls-actions.js'
import './example-realistic-demo/delivery-client.js'
import './example-realistic-demo/routing.js'
import './example-realistic-demo/views.js'
import './example-realistic-demo/connection.js'
import './example-realistic-demo/membership.js'
import './example-realistic-demo/approvals.js'
import './example-realistic-demo/apply-entry.js'
import './example-realistic-demo/timeline.js'
import './example-realistic-demo/chat.js'
import './example-realistic-demo/session.js'
import './example-realistic-demo/group-lock.js'

// Codec tests
import './codec/authenticated-content.js'
import './codec/capabilities.js'
import './codec/commit.js'
import './codec/composite.js'
import './codec/content-type.js'
import './codec/credential.js'
import './codec/credential-type.js'
import './codec/encrypted-group-secrets.js'
import './codec/extension.js'
import './codec/extension-type.js'
import './codec/external-sender.js'
import './codec/framed-content.js'
import './codec/group-context.js'
import './codec/group-info.js'
import './codec/group-secrets.js'
import './codec/hpke-ciphertext.js'
import './codec/key-package.js'
import './codec/key-package-tbs.js'
import './codec/leaf-node.js'
import './codec/leaf-node-data.js'
import './codec/leaf-node-source.js'
import './codec/lifetime.js'
import './codec/message.js'
import './codec/node-type.js'
import './codec/number.js'
import './codec/optional.js'
import './codec/padding.js'
import './codec/parent-hash.js'
import './codec/parent-node.js'
import './codec/presharedkey.js'
import './codec/private-content-aad.js'
import './codec/private-message.js'
import './codec/proposal.js'
import './codec/proposal-or-ref.js'
import './codec/proposal-or-ref-type.js'
import './codec/proposal-type.js'
import './codec/protocol-version.js'
import './codec/psk-id.js'
import './codec/psk-info.js'
import './codec/psk-label.js'
import './codec/psk-type.js'
import './codec/public-message.js'
import './codec/ratchet-tree.js'
import './codec/required-capabilities.js'
import './codec/resumption-psk-usage.js'
import './codec/reuse-guard.js'
import './codec/sender.js'
import './codec/sender-data.js'
import './codec/sender-data-aad.js'
import './codec/sender-type.js'
import './codec/transcript-hash.js'
import './codec/tree-hash.js'
import './codec/update-path.js'
import './codec/update-path-node.js'
import './codec/var-length-encoding.js'
import './codec/welcome.js'
import './codec/wireformat.js'

// Crypto tests
import './crypto/aead.js'
import './crypto/hash.js'
import './crypto/hpke.js'
import './crypto/signature.js'
import './crypto/signature-interop.js'

// Scenario tests
import './scenario/mixed-provider-interop.js'
import './scenario/non-extractable-identity.js'

// Test-vectors tests
import './test-vectors/crypto-basics.js'
import './test-vectors/deserialization.js'
import './test-vectors/key-schedule.js'
import './test-vectors/message-protection.js'
import './test-vectors/messages.js'
import './test-vectors/passive-client-scenarios.js'
import './test-vectors/psk-secret.js'
import './test-vectors/secret-tree.js'
import './test-vectors/transcript-hashes.js'
import './test-vectors/treekem.js'
import './test-vectors/treemath.js'
import './test-vectors/tree-operations.js'
import './test-vectors/tree-validation.js'
import './test-vectors/welcome.js'
